### ISSUE TITLE
[Wit] error: The request timed out. (code: -1001)

### ISSUE THREAD

**Issue by tielur** [wit-ai/wit-ios#50]
I'm getting this error when using the SDK. It seems to be related to the length of the recording ( about ~ 15 seconds ). I've set the vadTimeout to 15000.

``` objective-c
[Wit sharedInstance].vadTimeout = 15000;
```

The error is happening [here](https://github.com/wit-ai/wit-ios-sdk/blob/master/Wit/WITUploader.m#L88-L92)
The localizedDescription is:

> Got connection error: The request timed out.

Has anyone seen anything like this? I'm not sure what's going on. I've reached out to Wit support as well.

**Comment by l5t** [comment]
Hi Tyler,
Thanks for reporting, with long audio, we have experienced for the last couple of week an increased response time. It is very likely that the time out comes from there... We hope to have more info on the timing to decrease the response time in the next 2 weeks
Sorry for the inconvenience

**Comment by theiosdevguy** [comment]
I am facing the exact issue. With audio of about 15 seconds its working fine. But when audio is more than 15 seconds, the api returns timeout. Please suggest a way around.
