### ISSUE TITLE
Wit with audio file -ios ?

### ISSUE THREAD

**Issue by Ankish** [wit-ai/wit-ios#55]
Can we have a feature to send location of a file or raw recorded file and get the wit response ?
https://wit.ai/blog/2013/11/05/ios-and-speech
Seems to be redirecting to a broken link

**Comment by tielur** [comment]
It doesn't look like the iOS SDK supports sending a file, but you can send it directly via HTTP, these might be the docs you were trying to find:

https://wit.ai/docs/http/20141022#get-intent-via-speech-link
