### ISSUE TITLE
sendAsynchronousRequest:queue:completionHandler is deprecated: first deprecated in iOS 9

### ISSUE THREAD

**Issue by jmolayem** [wit-ai/wit-ios#61]
Getting a warning in Wit.m file (see above). The recorder is also a little buggy. This warning may be related. Just a heads up - this is a post iOS 9 issue.

**Comment by jasonhotsauce** [comment]
I think this SDK might be a little bit outdated since it's still using `NSURLConnection`, but since it still supports iOS 6 (which is not necessary, I think), it might be intended. 🍻
