### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by louisandkatherine** [wit-ai/wit-ios#63]
Am I doing something wrong or is arm64 not supported. I am getting these errors:

Undefined symbols for architecture arm64:
[TRACE]   "_vDSP_zvabs", referenced from:
[TRACE]       -[WITVad get_fft:] in libcom.firstutility.wit.a(WITVad.o)
[TRACE]   "_vDSP_ctoz", referenced from:
[TRACE]       -[WITVad get_fft:] in libcom.firstutility.wit.a(WITVad.o)
[TRACE]   "_vDSP_fft_zrip", referenced from:
[TRACE]       -[WITVad get_fft:] in libcom.firstutility.wit.a(WITVad.o)
[TRACE]   "_vDSP_create_fftsetup", referenced from:
[TRACE]       -[WITVad init] in libcom.firstutility.wit.a(WITVad.o)

**Comment by l5t** [comment]
Unfortunately we don't support yet arm64: https://github.com/wit-ai/wit-ios-sdk/issues/14#issuecomment-40226210

**Comment by louisandkatherine** [comment]
Thanks for your reply,
I've managed to get things working sort of but i'm getting an issue to do with timeout, is there any way around this?
[DEBUG] Firing app event: orientationChange[DEBUG] Starting......................[DEBUG] Firing app event: orientationChange[DEBUG] Stopping......................[ERROR] when enqueuing buffer from callback: -66632[ERROR] when enqueuing buffer from callback: -66632[ERROR] when enqueuing buffer from callback: -66632[ERROR] when enqueuing buffer from callback: -66632[ERROR] when enqueuing buffer from callback: -66632
[DEBUG] Could not successfully update network info during initialization.[DEBUG] [Wit] error: The request timed out.[DEBUG] Wit stopped recording because of a (network?) error[INFO]  witFailedToRespondCorrectly[INFO]  Clean WITRecorder[INFO]  Clean WITVad
 

    On Monday, 11 April 2016, 17:17, Laurent Landowski <notifications@github.com> wrote:
 

 Unfortunately we don't support yet arm64: #14 (comment)—
