### ISSUE TITLE
Request timed out

### ISSUE THREAD

**Issue by louisandkatherine** [wit-ai/wit-ios#65]
Hi i am getting this issue when building for ios

I've managed to get things working sort of but i'm getting an issue to do with timeout, is there any way around this?

[DEBUG] Firing app event: orientationChange
[DEBUG] Starting......................
[DEBUG] Firing app event: orientationChange
[DEBUG] Stopping......................
[ERROR] when enqueuing buffer from callback: -66632
[ERROR] when enqueuing buffer from callback: -66632
[ERROR] when enqueuing buffer from callback: -66632
[ERROR] when enqueuing buffer from callback: -66632
[ERROR] when enqueuing buffer from callback: -66632

[DEBUG] Could not successfully update network info during initialization.
[DEBUG] [Wit] error: The request timed out.
[DEBUG] Wit stopped recording because of a (network?) error
[INFO]  witFailedToRespondCorrectly
[INFO]  Clean WITRecorder
[INFO]  Clean WITVad

**Comment by theiosdevguy** [comment]
Facing the same issue. Anyone has a solution to this?
